on:
  pull_request:

jobs:
  pre-commit:
    uses: agblox/github-reusable-workflows/.github/workflows/pre-commit.yml@v0.4.3
    with:
      python-version: "3.10.2"

  commitlint:
    uses: agblox/github-reusable-workflows/.github/workflows/commitlint.yml@v0.4.3

  approve:
    if: ${{ success() }}
    needs:
      - pre-commit
      - commitlint
    uses: agblox/github-reusable-workflows/.github/workflows/approve.yml@v0.4.3
    secrets:
      token: ${{ secrets.ORG_MACHINE_USER_TOKEN }}

#  debug-default:
#    uses: agblox/github-reusable-workflows/.github/workflows/debug.yml@DD-590-fix
#
#  debug-false:
#    uses: agblox/github-reusable-workflows/.github/workflows/debug.yml@DD-590-fix
#    with:
#      flag: false
#
#  debug-true:
#    uses: agblox/github-reusable-workflows/.github/workflows/debug.yml@DD-590-fix
#    with:
#      flag: true
