on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: Check all files with pre-commit
    steps:
      - uses: actions/checkout@v2
      - uses: pre-commit/action@v2.0.3

  commitlint:
    uses: agblox/github-reusable-workflows/.github/workflows/commitlint.yml@DD-590-a

  approve:
    if: ${{ success() }}
    needs:
      - pre-commit
      - commitlint
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2
        with:
          github-token: "${{ secrets.ORG_MACHINE_USER_TOKEN }}"
