name: debug

on:
  workflow_call:
    inputs:
      flag:
        default: false
        description: Boolean flag
        required: false
        type: boolean

jobs:
  flag:
    runs-on: ubuntu-latest
    name: Test boolean flag
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Flag set
        if: inputs.flag
        run: echo 'flag value ${{ inputs.flag }}'
      - name: Flag not set
        if: ${{ ! inputs.flag }}
        run: echo 'flag value ${{ inputs.flag }}'
