on:
  push:
    branches:
      - master

jobs:
  pre-commit:
    uses: agblox/github-reusable-workflows/.github/workflows/pre-commit.yml@v0.4.3
    with:
      python-version: "3.10.2"

  release:
    uses: agblox/github-reusable-workflows/.github/workflows/release-workflow.yml@v0.4.3
    secrets:
      token: ${{ secrets.ORG_MACHINE_USER_TOKEN }}

  slack-workflow-status:
    if: ${{ failure() }}
    name: Post Workflow Status To Slack
    needs:
      - release
    uses: agblox/github-reusable-workflows/.github/workflows/status-to-slack.yml@v0.4.3
    secrets:
      slack-webhook: ${{ secrets.GIT_SLACK_WEBHOOK }}
